name: Nest.js CD Pipeline

on:
  push:
    branches:
      - main  # 监听的分支，可以根据需要更改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Node.js 版本，须根据项目需要调整

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to server
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USERNAME: ${{ secrets.DEPLOY_USER }}
        PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        TARGET_DIR: /var/www/workflow_demo
      run: |
        ssh -o StrictHostKeyChecking=no -i "$PRIVATE_KEY" "$USERNAME@$HOST" "mkdir -p $TARGET_DIR"
        # scp -i "$PRIVATE_KEY" -r dist/* "$USERNAME@$HOST:$TARGET_DIR"
    # 根据需要补充其他部署步骤
